# Generated by Django 3.1.5 on 2021-02-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, to='user_profiles.Courses'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='bio',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='teach_courses',
            field=models.ManyToManyField(blank=True, to='user_profiles.Courses'),
        ),
    ]
