# Generated by Django 3.1.5 on 2021-02-26 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_auto_20210201_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_profiles.schools'),
        ),
    ]
